spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zy-community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.zy_admin.**.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  level:
    com.example.demo99.mapper: DEBUG


